# https://numtide.github.io/devshell
[devshell]
packages = [
  "google-cloud-sdk",
  "go_1_18",
  "gopls",
  "gotools",
  "go-tools"
]
[[commands]]
package = "devshell.cli"
help = "Per project developer environments"
